---
title: "Desafio 1.0"
output: html_document
---

```{r}
library(readxl)
library(dplyr)
##se utilisa scipen=999 para que no lea los numeros con notacion cientifica
options(scipen = 999)

donacionesDATA <- read_excel("~/GitHub/desafio1/Donaciones_2017.xlsx", 
    col_types = c("numeric", "date", "text", 
        "numeric", "text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric"))
##se seleccionan las columnas de: año, nombre proyecto, donatario, donante, rut y monto total donacion
donaciones <- donacionesDATA[, c(1, 3, 5, 7, 8, 11)]

##se extrae base de datos de proyectos con atributo "nombre region" de link: https://datasocial.ministeriodesarrollosocial.gob.cl/donaciones/proyectos/3
proyectosDATA <- read_xlsx("DonacionesProyectos.xlsx")
proyectos1 <- select(proyectosDATA, 'NOMBRE INSTITUCIÓN', 'NOMBRE PROYECTO', 'FECHA APROBACIÓN','NOMBRE REGIÓN(ES)', 'ÁMBITO ACCIÓN')
proyectos1 <- rename(proyectos1, c("NOMBRE DEL PROYECTO"="NOMBRE PROYECTO"))
proyectos1 <- rename(proyectos1, c("DONATARIO"="NOMBRE INSTITUCIÓN"))

##con slice() se eliminan las filas con pryectos repetidos
proyectos1 <- slice(group_by(proyectos1, `NOMBRE DEL PROYECTO`), 1)
##misma linea pero con %>% 
##proyectos1 <- proyectos1 %>%
##              group_by(`NOMBRE DEL PROYECTO`) %>%
##              slice(1)
```

```{r}
library(stringr)
##se utiliza la libreria stringr para homogenizar nombres variables para conectar
donaciones$`NOMBRE DEL PROYECTO` <- str_trim(donaciones$`NOMBRE DEL PROYECTO`, side = "both")
proyectos1$`NOMBRE DEL PROYECTO` <- str_trim(proyectos1$`NOMBRE DEL PROYECTO`, side = "both")
donaciones$`DONATARIO` <- str_trim(donaciones$`DONATARIO`, side = "both")
proyectos1$`DONATARIO` <- str_trim(proyectos1$`DONATARIO`, side = "both")

donaciones$`NOMBRE DEL PROYECTO` <- toupper(donaciones$`NOMBRE DEL PROYECTO`)
proyectos1$`NOMBRE DEL PROYECTO` <- toupper(proyectos1$`NOMBRE DEL PROYECTO`)
donaciones$`DONATARIO` <- toupper(donaciones$`DONATARIO`)
proyectos1$`DONATARIO` <- toupper(proyectos1$`DONATARIO`)
proyectos1$`NOMBRE REGIÓN(ES)` <- toupper(proyectos1$`NOMBRE REGIÓN(ES)`)

donaciones$`NOMBRE DEL PROYECTO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          donaciones$`NOMBRE DEL PROYECTO`)
proyectos1$`NOMBRE DEL PROYECTO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`NOMBRE DEL PROYECTO`)
donaciones$`DONATARIO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          donaciones$`DONATARIO`)
proyectos1$`DONATARIO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`DONATARIO`)
proyectos1$`NOMBRE REGIÓN(ES)` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`NOMBRE REGIÓN(ES)`)

library(tidyverse)
proyectos1 <- separate(proyectos1, `NOMBRE REGIÓN(ES)`, into = c("Región 1", "Región 2", "Región 3","Región 4", "Región 5", "Región 6","Región 7", "Región 8", "Región 9","Región 10", "Región 11", "Región 12","Región 13", "Región 14", "Región 15"), sep = ",")

aux<-unique(donaciones %>% select(`NOMBRE DEL PROYECTO`, `DONATARIO`))

mergedonacionesproyectosaux <- merge(aux, proyectos1, by = c("NOMBRE DEL PROYECTO", "DONATARIO"))

##intento separacion de columnas regiones
##proyectos1$`NOMBRE REGIÓN(ES)` = strsplit(proyectos1$`NOMBRE REGIÓN(ES)`, split=", ")

##listaRegiones <- strsplit(proyectos1$`NOMBRE REGIÓN(ES)`,",",fixed=TRUE)
##m <- max(sapply(listaRegiones, length))
##dataRegiones <- do.call(rbind, lapply(listaRegiones, function(x) {c(x,rep(NA,m))[1:m]}))
```

```{r}
# Cargamos credenciales de .Renviron
# API key se obtiene para este caso en
# https://datos.observatoriologistico.cl/developers/
api_key<-"yIXuxN8JDzo66w2fuVsYVEvLeuqyzHNQIxsa2Ltx"
##install.packages("devtools")
library(devtools)
##devtools::install_github("FvD/junr")
library("junr")
# https://mran.microsoft.com/snapshot/2017-02-04/web/packages/junr/README.html
# Descargamos datos del pib regional
base_url <- "https://api.datos.observatoriologistico.cl/api/v2/datastreams/"
dataOBSLog <- get_data(base_url, api_key,"POBLA-DE-CHILE-2002-2020")

dataOBSLog <- rename(dataOBSLog, c("NOMBRE REGIÓN(ES)"="REGIÓN"))
dataOBSLog <- filter(dataOBSLog, AÑO==2004)
dataOBSLog$`NOMBRE REGIÓN(ES)` <- toupper(dataOBSLog$`NOMBRE REGIÓN(ES)`)
dataOBSLog$`NOMBRE REGIÓN(ES)` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          dataOBSLog$`NOMBRE REGIÓN(ES)`)
dataOBSLog$POBLACIÓN <- gsub('[,]', '', dataOBSLog$POBLACIÓN)
dataOBSLog$POBLACIÓN <- as.numeric(dataOBSLog$POBLACIÓN)

dataOBSLog1 <- summarise(group_by(dataOBSLog, `NOMBRE REGIÓN(ES)`),POBLACIÓN = sum(POBLACIÓN), n = n())

dataOBSLog1$`NOMBRE REGIÓN(ES)` <- 
  gsub('AYSEN DEL GENERAL CARLOS IBANEZ DEL CAMPO', 'AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO', dataOBSLog1$`NOMBRE REGIÓN(ES)`)
dataOBSLog1$`NOMBRE REGIÓN(ES)` <- 
  gsub("LIBERTADOR GENERAL BERNARDO O'HIGGINS", "LIBERTADOR GRAL.BERNARDO O’HIGGINS", dataOBSLog1$`NOMBRE REGIÓN(ES)`)

##se agrega mergedonacionesproyecto1 por si hay algun error en el desarrollo
library(reshape2)
mergedonacionesproyectos1 <- melt(mergedonacionesproyectos, id.vars = c("NOMBRE DEL PROYECTO", "DONATARIO", "AÑO", "DONANTE", "RUT", "MONTO TOTAL DONACIÓN", "FECHA APROBACIÓN", "ÁMBITO ACCIÓN"))


listaregiones <- unique(mergedonacionesproyectos1[,c(1,10)])
mergedonacionesproyectos1 <- dcast(mergedonacionesproyectos1, formula = `NOMBRE DEL PROYECTO`+DONATARIO+AÑO+DONANTE+RUT+`MONTO TOTAL DONACIÓN`+`FECHA APROBACIÓN`+`ÁMBITO ACCIÓN` ~ value, fun.aggregate = length)

```

```{r, echo=FALSE}
library(reticulate)
use_python("/usr/local/bin/python")
```

```{python, echo=FALSE}
import pandas
mergedonacionesproyectos2 = r.mergedonacionesproyectos1
mergedonacionesproyectos2.loc[mergedonacionesproyectos2.ANTOFAGASTA>0,'ANTOFAGASTA']=1
```

```{r}
mergedonacionesproyectos2$` ANTOFAGASTA`[mergedonacionesproyectos2$` ANTOFAGASTA` > 1] <- 1
mergedonacionesproyectos2$`LA ARAUCANIA`[mergedonacionesproyectos2$`LA ARAUCANIA` > 1] <- 1
mergedonacionesproyectos2$`LIBERTADOR GRAL.BERNARDO O’HIGGINS`[mergedonacionesproyectos2$`LIBERTADOR GRAL.BERNARDO O’HIGGINS` > 1] <- 1
mergedonacionesproyectos2$`METROPOLITANA DE SANTIAGO`[mergedonacionesproyectos2$`METROPOLITANA DE SANTIAGO` > 1] <- 1
mergedonacionesproyectos2$TARAPACA[mergedonacionesproyectos2$TARAPACA > 1] <- 1
mergedonacionesproyectos2$` ARICA Y PARINACOTA`[mergedonacionesproyectos2$` ARICA Y PARINACOTA` > 1] <- 1
mergedonacionesproyectos2$` ATACAMA`[mergedonacionesproyectos2$` ATACAMA` > 1] <- 1
mergedonacionesproyectos2$` AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO`[mergedonacionesproyectos2$` AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO` > 1] <- 1
mergedonacionesproyectos2$` BIOBIO`[mergedonacionesproyectos2$` BIOBIO` > 1] <- 1
mergedonacionesproyectos2$` COQUIMBO`[mergedonacionesproyectos2$` COQUIMBO` > 1] <- 1
mergedonacionesproyectos2$` LA ARAUCANIA`[mergedonacionesproyectos2$` LA ARAUCANIA` > 1] <- 1
mergedonacionesproyectos2$`LIBERTADOR GRAL.BERNARDO O’HIGGINS`[mergedonacionesproyectos2$`LIBERTADOR GRAL.BERNARDO O’HIGGINS` > 1] <- 1
mergedonacionesproyectos2$` LOS LAGOS`[mergedonacionesproyectos2$` LOS LAGOS` > 1] <- 1
mergedonacionesproyectos2$` LOS RIOS`[mergedonacionesproyectos2$` LOS RIOS` > 1] <- 1
mergedonacionesproyectos2$` MAGALLANES Y DE LA ANTARTICA CHILENA`[mergedonacionesproyectos2$` MAGALLANES Y DE LA ANTARTICA CHILENA` > 1] <- 1

```

```{r}
mergedonacionesproyectos2 <- mergedonacionesproyectos1
mergedonacionesproyectos2$`LA ARAUCANIA` <- 
for(i in mergedonacionesproyectos2$`LA ARAUCANIA`){  
  if (i > 0)
  {mergedonacionesproyectos2$`LA ARAUCANIA`=1}
}

mergedonacionesproyectos1 <- rename(mergedonacionesproyectos1, c("NOMBRE REGIÓN(ES)"="value"))

mergedonacionesproyectos <- merge(mergedonacionesproyectos, dataOBSLog1, by = c("NOMBRE REGIÓN(ES)"))



##dataOBSLog1 <- rename(dataOBSLog1, c("Región 1"="NOMBRE REGIÓN(ES)"))
##mergedonacionesAPI <- merge(mergedonacionesproyectos, dataOBSLog1, by = c("NOMBRE DEL PROYECTO", "DONATARIO"))




##dataOBS - proyectos1
##LIBERTADOR GENERAL BERNARDO O'HIGGINS - LIBERTADOR GRAL.BERNARDO O’HIGGINS
##BIO-BIO - BIOBIO
##ARAUCANIA - LA ARAUCANIA
##AISEN DEL GENERAL CARLOS IBANEZ DEL CAMPO - AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO
##

mergeprueba <- mergedonacionesproyectos

##cambio formato de fechas
mergeprueba$`FECHA APROBACIÓN` <- format(mergeprueba$`FECHA APROBACIÓN`,"%d/%m/%Y") 

##cambio letras a mayusculas
mergeprueba$`DONANTE` <- toupper(mergeprueba$`DONANTE`)
mergeprueba$`DONATARIO` <- toupper(mergeprueba$`DONATARIO`)

##homogenizacion ruts
mergeprueba$RUT <- gsub('[.]', '', mergeprueba$RUT)
listaRutSinGuion <- substr(mergeprueba$RUT, 1, (nchar(mergeprueba$RUT)-1))
listaGuionesRut <- substr(mergeprueba$RUT, nchar(mergeprueba$RUT), nchar(mergeprueba$RUT))
mergeprueba$RUT <- paste0(listaRutSinGuion, sep="-", listaGuionesRut)

##homogenizacion montos
mergeprueba$`MONTO TOTAL DONACIÓN` <- gsub('[$]', '', mergeprueba$`MONTO TOTAL DONACIÓN`)
mergeprueba$`MONTO TOTAL DONACIÓN` <- gsub('[.]', '', mergeprueba$`MONTO TOTAL DONACIÓN`)


##x <- data.frame(proyecto = 1:4, región = c("10.550,4", "10,550.4", "19550,4", "19550.4"))
##x$región <- as.double(x$región)

```







