---
title: "DESAFIO 1 INTENTO 3"
output: html_document
---

```{r}
rm(list = ls())
library(readxl)
library(dplyr)
library(stringr)
##se utilisa scipen=999 para que no lea los numeros con notacion cientifica
options(scipen = 999)
donacionesDATA <- read_excel("~/GitHub/desafio1/Donaciones_2017.xlsx", 
    col_types = c("numeric", "date", "text", 
        "numeric", "text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric"))
##se seleccionan las columnas de: año, nombre proyecto, donatario, donante, rut y monto total donacion
donaciones <- donacionesDATA[, c(1, 3, 5, 7, 8, 11)]
##usamos unique() para ver solo nombres de proyectos no repetidos
paresProyectosDonatarios <- select(donaciones,"NOMBRE DEL PROYECTO", "DONATARIO")
paresProyectosDonatarios <- unique(paresProyectosDonatarios)

##se extrae una base de datos de proyectos con atributo "nombre region" del link: https://datasocial.ministeriodesarrollosocial.gob.cl/donaciones/proyectos/3
proyectosDATA <- read_xlsx("DonacionesProyectos.xlsx")
##se seleccionan las columnas que nos sirven para el estudio, y se homogenizan los nombres de las columnas
proyectos1 <- select(proyectosDATA, 'NOMBRE INSTITUCIÓN', 'NOMBRE PROYECTO', 'FECHA APROBACIÓN','NOMBRE REGIÓN(ES)', 'ÁMBITO ACCIÓN')
proyectos1 <- rename(proyectos1, c("NOMBRE DEL PROYECTO"="NOMBRE PROYECTO"))
proyectos1 <- rename(proyectos1, c("DONATARIO"="NOMBRE INSTITUCIÓN"))

##homogenizamos los valores de variables para cruzar informacion
##con str_trim() eliminamos los espacios que sobran antes y despues de cada valor
paresProyectosDonatarios$`NOMBRE DEL PROYECTO` <- str_trim(paresProyectosDonatarios$`NOMBRE DEL PROYECTO`, side = "both")
proyectos1$`NOMBRE DEL PROYECTO` <- str_trim(proyectos1$`NOMBRE DEL PROYECTO`, side = "both")
paresProyectosDonatarios$`DONATARIO` <- str_trim(paresProyectosDonatarios$`DONATARIO`, side = "both")
proyectos1$`DONATARIO` <- str_trim(proyectos1$`DONATARIO`, side = "both")
##con toupper() llevamos a mayusculas todos los datos que nos interesan
paresProyectosDonatarios$`NOMBRE DEL PROYECTO` <- toupper(paresProyectosDonatarios$`NOMBRE DEL PROYECTO`)
proyectos1$`NOMBRE DEL PROYECTO` <- toupper(proyectos1$`NOMBRE DEL PROYECTO`)
paresProyectosDonatarios$`DONATARIO` <- toupper(paresProyectosDonatarios$`DONATARIO`)
proyectos1$`DONATARIO` <- toupper(proyectos1$`DONATARIO`)
proyectos1$`NOMBRE REGIÓN(ES)` <- toupper(proyectos1$`NOMBRE REGIÓN(ES)`)
##con chartr() reemplazamos los caracteres que pueden generar problemas como los tildes y la Ñ
paresProyectosDonatarios$`NOMBRE DEL PROYECTO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          paresProyectosDonatarios$`NOMBRE DEL PROYECTO`)
proyectos1$`NOMBRE DEL PROYECTO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`NOMBRE DEL PROYECTO`)
paresProyectosDonatarios$`DONATARIO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          paresProyectosDonatarios$`DONATARIO`)
proyectos1$`DONATARIO` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`DONATARIO`)
proyectos1$`NOMBRE REGIÓN(ES)` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          proyectos1$`NOMBRE REGIÓN(ES)`)

```

AL COMIENZO UTILIZAMOS ESTE CODIGO PARA HOMOGENIZAR NOMBRES, Y FUNCIONÓ BIEN, PERO LUEGO TUVIMOS PROBLEMAS CON LA LIBRERIA FUZZYWUZZYR, Y SE OPTO POR UTILIZAR PYHTON.
```{r}
##install.packages('fuzzywuzzyR')
##devtools::install_github(repo = 'mlampros/fuzzywuzzyR')
##library(fuzzywuzzyR)
##x <- c("frodo baggins","new yorks","daddy yankee")
##y <- c("frodo bag", "new york", "daddy yanke")
##numerox <- as.integer(length(x))
##numeroy <- as.integer(length(y))
##for (i in 1:numerox){
  ##s1 = x[i]
  ##for (j in 1:numeroy){
    ##s2 = y[j]
    ##init = SequenceMatcher$new(string1 = s1, string2 = s2)
    ##ratio = init$ratio()
    ##if (ratio >0.9){
      ##y[j] <- x[i]
    ##}
  ##}
##}
```

```{r}
##se utilizara pyhton para homogenizar nombres segun ratio de fuzzywuzzy
library(reticulate)
use_python("/usr/local/bin/python")
##seleccionamos nombres de proyectos para homogenizar
x <- proyectos1$`NOMBRE DEL PROYECTO`
y <- paresProyectosDonatarios$`NOMBRE DEL PROYECTO`
y <- as.data.frame(y)
```

```{python}
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
```

```{python}
##el proyecto "GESTION Y ACOMPANAMIENTO PROYECTOS AMERICA SOLIDARIA CHILE" se repite muchas veces pero con un nombre que agrega un numero por cada Donante, sin embargo es un mismo proyecto, por lo que se homogeniza el nombre para eliminar repetidos
x = r.x
y = r.y
contj = -1
for i in y:
    contj = contj+1
    if fuzz.token_set_ratio("GESTION Y ACOMPANAMIENTO PROYECTOS AMERICA SOLIDARIA CHILE", i)==100:
        y[contj] = "GESTION Y ACOMPANAMIENTO PROYECTOS AMERICA SOLIDARIA CHILE 2017"
        print(f"{y[contj]}")
```


```{r}
##aplicamos unique() para eliminar proyectos repetidos, ya que solo trabajaremos con su nombre
x <- as.data.frame(py$x)
x <- unique(x)
x <- x$`py$x`

y <- as.data.frame(py$y)
y <- unique(y)
y <- y$`py$y`
##podemos observar todos los nombres de proyectos sin que se repitan
```

```{python}
##se homogenizan nombres de proyectos con semejanza mayor a 90% en los caracteres
x = r.x
y = r.y
conti = -1
for i in x:
    conti = conti + 1
    contj = -1
    for j in y:
        contj = contj + 1
        if  fuzz.ratio(i,j) > 90:
            y[contj] = x[conti]

##podemos usar print() para ver los resultados que cambiaron el nombre
##print(f"i= {i} y j= {j}")
##print(f"i= {x[conti]} y j= {y[contj]}")
```


```{r}
##podemos utilizar print() para anotar las coincidencias erroneas, y poder arreglarlas despues
##ahora vemos todas las coincidencias de nombres que existian entre nuestras dos bases de datos iniciales: donacionesDATA y proyectosDATA
x <- as.data.frame(py$x)
y <- as.data.frame(py$y)
x <- rename(x, c("NOMBRE DEL PROYECTO"="py$x"))
y <- rename(y, c("NOMBRE DEL PROYECTO"="py$y"))
mergexy <- merge(x, y, by = c("NOMBRE DEL PROYECTO"))
##con mergexy nos damos cuenta que solo tenemos 111 coincidencias, ahora veremos que pasa con las 117 restantes

##creamos dataframex para agregarle un 1 a los numeros que se utilizara despues para representar los nombres que no hicieron mach
dataframex <- data.frame(`NOMBRE DEL PROYECTO`=x$`NOMBRE DEL PROYECTO`, donacionesx = 1)
dataframex <- rename(dataframex, c("NOMBRE DEL PROYECTO"="NOMBRE.DEL.PROYECTO"))
##en mergexy2 finalmente tenemos todos los nombres de proyectosDATA que no hicieron match
mergexy2 <- merge(dataframex, y, by = c("NOMBRE DEL PROYECTO"), all.x = TRUE, all.y = TRUE )
mergexy2 <- filter(mergexy2, is.na(donacionesx))
mergexy2 <- mergexy2$`NOMBRE DEL PROYECTO`

##creamos dataframey para lo mismo que dataframex
dataframey <- data.frame(`NOMBRE DEL PROYECTO`=y$`NOMBRE DEL PROYECTO`, donacionesy = 1)
dataframey <- rename(dataframey, c("NOMBRE DEL PROYECTO"="NOMBRE.DEL.PROYECTO"))
##en mergexyXsinmatch tenemos todos los nombres de donacionesDATA que no hicieron match
mergexyXsinmatch <- merge(x, dataframey, by = c("NOMBRE DEL PROYECTO"), all.x = TRUE, all.y = TRUE )
mergexyXsinmatch <- filter(mergexyXsinmatch, is.na(donacionesy))
mergexyXsinmatch <- mergexyXsinmatch$`NOMBRE DEL PROYECTO`
```

```{python}
##esta vez utilizamos fuzz.token_set_ratio() para encontrar nuevas coincidencias, esta funcion compara palabras enteras, por lo que exigimos el 100% de ratio de coincidencia para no generar problemas nombres de proyectos similares
mergexyXsinmatch = r.mergexyXsinmatch
mergexy2 = r.mergexy2
conti = -1
for i in mergexyXsinmatch:
    conti = conti + 1
    contj = -1
    for j in mergexy2:
        contj = contj + 1
        if  fuzz.token_set_ratio(i,j) == 100:
            mergexy2[contj] = mergexyXsinmatch[conti]
            print(f"i= {i} y j= {j}")
            print(f"i= {mergexyXsinmatch[conti]} y j= {mergexy2[contj]}")
```

```{r}
##ahora vamos a crear una variable llamada joinProyectos donde se guardaran todos los nombres de donacionesDATA que todavia no hacen match 
mergexy2 <- as.data.frame(py$mergexy2)
mergexy2 <- rename(mergexy2, c("NOMBRE DEL PROYECTO"="py$mergexy2"))

mergexyXsinmatch <- as.data.frame(mergexyXsinmatch)
mergexyXsinmatch <- rename(mergexyXsinmatch, c("NOMBRE DEL PROYECTO"="mergexyXsinmatch")) 

dataframex2 <- data.frame(`NOMBRE DEL PROYECTO`=mergexyXsinmatch$`NOMBRE DEL PROYECTO`, donacionesx = 1)
dataframex2 <- rename(dataframex2, c("NOMBRE DEL PROYECTO"="NOMBRE.DEL.PROYECTO")) 

joinProyectos <- merge(dataframex2, mergexy2, by = c("NOMBRE DEL PROYECTO"), all.x = TRUE, all.y = TRUE )
joinProyectos <- filter(joinProyectos, is.na(donacionesx))
##Observando joinproyectos podemos ver los nombres de proyectos que aun no tienen ninguna coincidencia, asi que se decide hacer una depuracion manual a los proyectos que faltan
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == '"CAPACITACION EN TALLERES INTEGRALES DE OFICIO A NNA QUE VIVEN EN CENTROS DE PROTECCION DE SENAME…"'] <- "CAPACITACIONES EN TALLERES INTEGRALES DE OFICIO A LOS NINOS, NINAS Y ADOLESCENTES QUE VIVEN EN CENTROS DE PROTECCION DEL SENAME PARA OCUPAR SUS TIEMPOS DE OCIO, EVITAR LAS MALAS PRACTICAS, DARLES UNA OPORTUNIDAD Y CONTRIBUIR A RECUPERAR SU CONFIANZA Y LA ESPERANZA"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == '"PREPARACION PARA LA VIDA INDEPENDIENTE DE LOS NNJ MAS VULNERABLES"'] <- "PREPARACION PARA LA VIDA INDEPENDIENTE DE LOS NNJ MAS VULNERADOS DE LA REGION METROPOLITANA"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "21 PLAZAS"] <- "21 PLAZAS RM"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "21 PLAZAS, RM (COLINA, CERRILLOS Y LAMPA)"] <- "21 PLAZAS RM"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "APOYO A LA GESTION E INTEGRACION EDUCATIVA DE ALHUE"] <- "GESTION E INTEGRACION EDUCATIVA EN ALHUE"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "APOYO A LA INTEGRACION SOCIAL Y LABORAL DE JOVENES CON DISCAPACIDAD COGNITIVA"] <- "PROGRAMA DE INCLUSION LABORAL DE JOVENES CON DISCAPACIDAD COGNITIVA LEVE-MODERADA"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "APOYO AL EMPRENDIMENTO LAFQUENCHE DE TIRUA"] <- "APOYO AL EMPRENDIMIENTO LAFQUENCHE DE TIRUA: “FRAMBUESAS, FENMAMELL TRIRWA WILLI (FRUTOS DEL ARBOL TIRUA SUR”)"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "APOYO AL EMPRENDIMIENTO AGROPECUARIO 30 FAMILIAS COLLIPULLI HUAPITRIO"] <- "APOYO EMPRENDIMIENTO AGROPECUARIO DE 30 FAMILIAS MAPUCHES DEL SECTOR HUAPITRIO, DE LA COMUNA DE COLLIPULLI"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "ATENCION INTEGRAL A LACTANTES Y PARVULOS VULNERADOS EN SUS DERECHOS"] <- "CASA DE LACTANTES Y PARVULOS HOGAR ESPERANZA"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "CENTRO PREV. DE LA VIOLENCIA JUVENIL ( CPVJ)"] <- "CENTRO DE PREVENCION DE LA VIOLENCIA JUVENIL"
mergexy2$`NOMBRE DEL PROYECTO`[mergexy2$`NOMBRE DEL PROYECTO` == "CONSTRIBUYENDO AL CRECIMIENTO Y DESARROLLO DE TALTAL"] <- "CONTRIBUYENDO AL CRECIMIENTO Y AL DESARROLLO DE LA COMUNA DE TALTAL"
##joinProyectos2$`NOMBRE DEL PROYECTO`[joinProyectos2$`NOMBRE DEL PROYECTO` == ""] <- ""

##ahora con merge() unimos todos los nombres que homogenizamos entre donacionesDATA y proyectosDATA
nombresDonacionesFinal <- merge(mergexy, mergexy2, all = TRUE)

##SE ELIMINAN PROYECTOS REPETIDOS PARA SEGUIR AVANZANDO EL EJERCICIO(6 DATOS), estan repetidos por que cuando usamos la funcion fuzzywuzzy algunos proyectos con nombres muy similares quedaron iguales, pero se decidio seguir avanzando puesto que no afectaria la conclusion final del ejercicio
nombresDonacionesFinal <- unique(nombresDonacionesFinal)

##hacemos un join segun los nombres de proyectos para agregar su geolocalizacion y otras caracteristicas de proyectosDATA
joinProyectosDonaciones <- merge(nombresDonacionesFinal, proyectos1, by = c("NOMBRE DEL PROYECTO"))
##obtuvimos 162 proyectos de un total de 228, que representa el 71% de los nombres de proyectos de donacionesDATA, se estima que es una buena cifra para seguir avanzando en las conclusiones del desafio
library(tidyverse)
##ahora utilizamos separate() para separar la columna de NOMBRE REGION(ES)
joinProyectosDonaciones <- separate(joinProyectosDonaciones, `NOMBRE REGIÓN(ES)`, into = c("Región 1", "Región 2", "Región 3","Región 4", "Región 5", "Región 6","Región 7", "Región 8", "Región 9","Región 10", "Región 11", "Región 12","Región 13", "Región 14", "Región 15"), sep = ",")
##Se utilizan solo 15 regiones, ya que se comprobo que los proyectos que mas regiones de impacto tienen es maximo 15
```

```{r}
##Obtenemos las instrucciones de la API en el siguiente link:
##https://datos.observatoriologistico.cl/dataviews/238730/poblacion-de-chile/
api_key<-"yIXuxN8JDzo66w2fuVsYVEvLeuqyzHNQIxsa2Ltx"
##install.packages("devtools")
library(devtools)
##devtools::install_github("FvD/junr")
library("junr")
##cargamos datos de la poblacion de chile atraves de la API
base_url <- "https://api.datos.observatoriologistico.cl/api/v2/datastreams/"
dataOBSLog <- get_data(base_url, api_key,"POBLA-DE-CHILE-2002-2020")

##se hace una homogenizacion a los datos, y se utilizan los datos del año 2004 ya que son los ultimos registros de poblacion completa que tiene la API, esto ocurre debido a que la API solo carga una muestra de el dataframe real
dataOBSLog <- rename(dataOBSLog, c("NOMBRE REGIÓN(ES)"="REGIÓN"))
dataOBSLog <- filter(dataOBSLog, AÑO==2004)
dataOBSLog$`NOMBRE REGIÓN(ES)` <- toupper(dataOBSLog$`NOMBRE REGIÓN(ES)`)
dataOBSLog$`NOMBRE REGIÓN(ES)` <- chartr('ÁÉÍÓÚÑ','AEIOUN',
                          dataOBSLog$`NOMBRE REGIÓN(ES)`)
dataOBSLog$POBLACIÓN <- gsub('[,]', '', dataOBSLog$POBLACIÓN)
dataOBSLog$POBLACIÓN <- as.numeric(dataOBSLog$POBLACIÓN)
##se agrupan los datos de poblacion segun su region
dataOBSLog1 <- summarise(group_by(dataOBSLog, `NOMBRE REGIÓN(ES)`),POBLACIÓN = sum(POBLACIÓN), n = n())
##se homogenizan nombres de regiones para hacer cruce con joinProyectosDonaciones
dataOBSLog1$`NOMBRE REGIÓN(ES)` <- 
  gsub('AYSEN DEL GENERAL CARLOS IBANEZ DEL CAMPO', 'AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO', dataOBSLog1$`NOMBRE REGIÓN(ES)`)
dataOBSLog1$`NOMBRE REGIÓN(ES)` <- 
  gsub("LIBERTADOR GENERAL BERNARDO O'HIGGINS", "LIBERTADOR GRAL.BERNARDO O’HIGGINS", dataOBSLog1$`NOMBRE REGIÓN(ES)`)

library(reshape2)
##se utiliza melt() para dejar nuestro dataframe en formato long
joinProyectosLong <- melt(joinProyectosDonaciones, id.vars = c("NOMBRE DEL PROYECTO", "DONATARIO", "FECHA APROBACIÓN", "ÁMBITO ACCIÓN"))
##utilizamos str_trim() por que algunas regiones quedan con espacios innecesarios al final
joinProyectosLong$value <- str_trim(joinProyectosLong$`value`, side = "both")
##utilizamos dcast() para dejar asociadas las regiones a cada proyecto en formato wide y binario
joinProyectosWide <- dcast(joinProyectosLong, formula = `NOMBRE DEL PROYECTO`+DONATARIO+`FECHA APROBACIÓN`+`ÁMBITO ACCIÓN` ~ value, fun.aggregate = length)

##eliminamos la columna numero 21, que la genera dcast() pero no sirve para el analisis futuro
joinProyectosWide <- joinProyectosWide[,c(1:20)]
##IMPORTANTE en la siguiente linea, esta la operacion que genera la potencial poblacion de impacto de cada proyecto, considerando la poblacion extraida de la API y las regiones asociada a cada proyecto
joinProyectosWide$`POBLACION DE IMPACTO` <- joinProyectosWide$ANTOFAGASTA * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("ANTOFAGASTA")), POBLACIÓN)) + joinProyectosWide$`ARICA Y PARINACOTA` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("ARICA Y PARINACOTA")), POBLACIÓN)) + joinProyectosWide$ATACAMA * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("ATACAMA")), POBLACIÓN)) + joinProyectosWide$`AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("AYSEN DEL GRAL. CARLOS IBANEZ DEL CAMPO")), POBLACIÓN)) + joinProyectosWide$BIOBIO * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("BIOBIO")), POBLACIÓN)) + joinProyectosWide$COQUIMBO * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("COQUIMBO")), POBLACIÓN)) + joinProyectosWide$`LA ARAUCANIA` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("LA ARAUCANIA")), POBLACIÓN)) + joinProyectosWide$`LIBERTADOR GRAL.BERNARDO O’HIGGINS` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("LIBERTADOR GRAL.BERNARDO O’HIGGINS")), POBLACIÓN)) + joinProyectosWide$`LOS LAGOS` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("LOS LAGOS")), POBLACIÓN)) + joinProyectosWide$`LOS RIOS` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("LOS RIOS")), POBLACIÓN)) + joinProyectosWide$`MAGALLANES Y DE LA ANTARTICA CHILENA` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("MAGALLANES Y DE LA ANTARTICA CHILENA")), POBLACIÓN)) + joinProyectosWide$MAULE * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("MAULE")), POBLACIÓN)) + joinProyectosWide$`METROPOLITANA DE SANTIAGO` * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("METROPOLITANA DE SANTIAGO")), POBLACIÓN)) + joinProyectosWide$NUBLE * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("NUBLE")), POBLACIÓN)) + joinProyectosWide$TARAPACA * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("TARAPACA")), POBLACIÓN)) + joinProyectosWide$VALPARAISO * as.numeric(select(filter(dataOBSLog1, as.character(`NOMBRE REGIÓN(ES)`) == as.character("VALPARAISO")), POBLACIÓN))
```

```{r}
##RESULTADOS

##1: podemos ordenar los proyectos segun la potencial poblacion de impacto
resultado1 <- joinProyectosWide[order(-joinProyectosWide$`POBLACION DE IMPACTO`), ]
##tambien podemos ver facilmente los proyectos que tienen impacto nacional (12 proyectos)
resultado1 <- filter(joinProyectosWide, `POBLACION DE IMPACTO` == 15562113)

##2: podemos ver la poblacion potencial de impacto de cada proyecto.
resultado2 <- select(joinProyectosWide, `NOMBRE DEL PROYECTO`, `POBLACION DE IMPACTO`)

##3: podemos ver la cantidad y proporcion de proyectos que tiene cada region
resultado3 <- joinProyectosWide[,c(1,5:20)]
resultado3 <- melt(resultado3, id.vars = c("NOMBRE DEL PROYECTO"))
resultado3 <- resultado3[,c(2,3)]
resultado3 <- summarise(group_by(resultado3, `variable`), value = sum(value), `total de proyectos`=n())
resultado3$`Proporcion con el pais` <- (resultado3$value/resultado3$`total de proyectos`)*100
resultado3 <- resultado3[,c(1,2,4)]
resultado3 <- rename(resultado3, c("numero de proyectos"="value"))

##3: podemos ver la poblacion potencial de impacto de cada proyecto.
resultado3 <- select(joinProyectosWide, `NOMBRE DEL PROYECTO`, `POBLACION DE IMPACTO`)

##4: podemos ver la poblacion potencial por cada donatario segun sus proyectos.
resultado4 <- joinProyectosWide[,c(2,21)]
resultado4 <- summarise(group_by(resultado4, `DONATARIO`), `POBLACION DE IMPACTO` = sum(`POBLACION DE IMPACTO`))

##5: podemos ver la cantidad de poblacion potencial por cada ambito de accion segun su cantidad de proyectos.
resultado5 <- joinProyectosWide[,c(4,21)]
resultado5 <- summarise(group_by(resultado5, `ÁMBITO ACCIÓN`), `POBLACION DE IMPACTO` = sum(`POBLACION DE IMPACTO`))
```